### ISSUE TITLE
https://www.youtube.com/watch?v=iljAdVFzEs4    this os our video link adjust it on the about page. 

### ISSUE THREAD

**Issue by Chitranshmittal** [karx/viragram-homepage#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Chitranshmittal** [comment]
please enlarge the media player it's
 very small.

**Comment by IAmSarthakVerma** [comment]
Done.

**Comment by IAmSarthakVerma** [comment]
@karx Update this issue.
