### ISSUE TITLE
Blogs are not showing on the internet, they are coming as Archive.

### ISSUE THREAD

**Issue by Chitranshmittal** [karx/viragram-homepage#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IAmSarthakVerma** [comment]
More explanation needed.

**Comment by Chitranshmittal** [comment]
come sit next to me then!

**Comment by Chitranshmittal** [comment]
![WhatsApp Image 2019-09-24 at 8 32 25 PM](https://user-images.githubusercontent.com/54746622/65523887-8aa13b00-df0a-11e9-920e-f84b7ebe9c04.jpeg)

**Comment by karx** [comment]
@IAmSarthakVerma to look into this and report.

**Comment by karx** [comment]
what is the status of this?
