### ISSUE TITLE
Logo is not aligned properly on the header 

### ISSUE THREAD

**Issue by Chitranshmittal** [karx/viragram-homepage#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by karx** [comment]
FIxing this for now.

Please try and attach screenshots whenever possible.
@Chitranshmittal Again asking you to at least maintain some standard.

**Comment by IAmSarthakVerma** [comment]
![Screenshot 2019-09-24 at 9 07 21 PM](https://user-images.githubusercontent.com/20480867/65526856-5f6d1a80-df0f-11e9-865d-9aec47e8fba8.png)
The logo is aligned but it seems "not aligned" because of your design. See the attached image.

**Comment by karx** [comment]
Can we vertical center align the menu items

**Comment by karx** [comment]
Can we close this now?
Nitin updated this.
