### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by karx** [karx/viragram-homepage#23]
http://52.91.31.91/

Something Sarthak has been trying out. Dekho Batao

**Comment by karx** [comment]
![image](https://user-images.githubusercontent.com/7826138/66870911-1bc27980-efc0-11e9-9da7-49dfc19df8f9.png)

**Comment by karx** [comment]
So the plan if we need to make this new website work. I talked to nitin and this is what we need in the next version

* Individual pages for Platforms.
Wordpress me categories, or tags pe khel lo, and make it the different platform.

* Portfolio page

* Services waala page wonked up

* The blogsz

**Comment by IAmSarthakVerma** [comment]
Portfolio page waiting from Designer

**Comment by karx** [comment]
Ping! @IAmSarthakVerma

**Comment by karx** [comment]
This move is almost complete. Further changes tracked in issues #28 #29 #30  #31
