### ISSUE TITLE
Update the new process video on the home page its with sarthak i guess.

### ISSUE THREAD

**Issue by Chitranshmittal** [karx/viragram-homepage#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IAmSarthakVerma** [comment]
Assigned to @iamsarthakverma

**Comment by IAmSarthakVerma** [comment]
Video is too big in size to be directly embedded. Either compress the size and mail me or upload to youtube and post a link here.

**Comment by Chitranshmittal** [comment]
https://www.youtube.com/watch?v=IfmmqTz_Ov4
