### ISSUE TITLE
please add the image of our Allies which is been shared with @iamsarthaverma on hs email id

### ISSUE THREAD

**Issue by Chitranshmittal** [karx/viragram-homepage#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IAmSarthakVerma** [comment]
Done! @karx Please update this issue.

**Comment by Chitranshmittal** [comment]
@IAmSarthakVerma put "Our Trusted Allies"

**Comment by Chitranshmittal** [comment]
we'll share the new image with you by tomorrow.

**Comment by karx** [comment]
I do not understand a word coming from @Chitranshmittal 

Please be more clear and verbose. Thanks
At least maintain some clarity and standard.

**Comment by IAmSarthakVerma** [comment]
@Chitranshmittal Fixed the heading for now. For new images, you have to upload that on your own. I have uploaded it once and I will not keep on updating with every new change that you got. Just go on About Us page > Edit > and find where the image is and change it.
